In [1]:
import scipy.stats as stats

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df=sns.load_dataset('tips')

In [6]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [19]:
dataset_table=pd.crosstab(df["sex"],df["smoker"])
dataset_table

smoker  Yes  No
sex            
Male     60  97
Female   33  54

In [20]:
dataset_table.values

array([[60, 97],
       [33, 54]], dtype=int64)

In [24]:
expected_values=stats.chi2_contingency(dataset_table)
expected_values

(0.0,
 1.0,
 1,
 array([[59.84016393, 97.15983607],
        [33.15983607, 53.84016393]]))

In [27]:
expected_values[3]

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

In [43]:
dataset_table

smoker  Yes  No
sex            
Male     60  97
Female   33  54

In [56]:
m=len(dataset_table.iloc[0:2,0])
m

2

In [57]:
n=len(dataset_table.iloc[0,0:2])
n

2

In [58]:
(n-1)*(m-1)

1

In [ ]:
  fo-fe/fe

In [59]:
p_value=1-chi2.cdf(x = chi_statistics , df = ddof)
print('p-value:',p_value)
print('Significance level: ',alpha)
print('Degree of Freedom : ',ddof)

NameError: name 'chi2' is not defined