In [ ]:
Sample_mean(x̄) 
Population_mean(µ)

########################################################

@Variance formula


Population_Variance (σ²)           Sample_Variance(s²)
--------------------------   |   --------------------------
                             |
Formula for Population       |       Formula for Sample  
Variance is                  |        Variance is
                             |
      N   (xi-µ)²            |            n   (xi-x̄)²
σ² =  ∑   ------             |      s² =  ∑   ------
     i=1     N               |           i=1    n-1    
                             |         
Here "µ" is "Population mean"|      Here "x̄" is the "Sample mean"

######################################################################

"Variance"(x)  to "Covariance"(x,x)  

           n    (xi-x̄)²          n   (x-x̄)*(x-x̄)
 Var(x) =  ∑  ----------   ==>   ∑ ------------- = covariance(x,x) 
          i=1    n-1            i=1      n-1
    
#####################################################################

@Pearson_Correlation_Coefficent :=
    
    The more towords +1 more positively correlation
    The more towords -1 more negatively correlated
    [:. ρ = row sign]
    
    
             Cov[x,y]
    ρ x,y = ------------  B-coz of this ["σx  σy"] it will 
              σx   σy     try to get "restricted" B/w"-1 to 1" 
                          The more the value towords 1 more 
                          +ve it is 'Correlated' 
                
#######################################################

@Spearman_Rank_Corelation :=
   
    in Spearman Rank Corelation we bassically createts "Rank"

according to 'spearmans rank correlation' we are able to get 
1, but "pearson correlation" when we find out that value
its  0.88

          Cov(R(x),R(y))
    rs = -----------------
          σR(x)   σR(y)
        
##############################################################

Chi-square test formula : =
    
    
              (f0 - fe)²      (obsered - expected)²
    X² =   ∑ ------------- = ----------------------
                 fe                expected
        
#############################################################

why Z-score need ?

    with the help of Z-score we will be understand 
    how many SD that particuler number folls away or
    bellow from the mean
    
                           xi - µ
                Z-score = --------
                              σ
                
#############################################################

                           xi - µ
                Z-score = -------- 
                             s/√n 

                           xi - µ
                Z-score = -------- 
                             σ/√n 
                    
##########################################################

respect to this 2 value(n,x) we can caluculate 
 the "propotion"
    
   "propotion" formula

             ^     x̄        
             P = -----  
                   n   
            
            
        x = 130  , n = 200
ex : = 
    ^     x̄       130 
    P = -----  = ----- = 0.65 = 65%
          n       200   
        
 "Z-test with Propotion"

now in order to aplly Z-test there will be a seperate
formula   

                 P^ - P0
       Z-test = ---------- [:. q0 is nothing but 1-P0]
                √(P0)(q0)/n
            
#############################################################

 @Covariance_Formula :=
        
                     n   (Xi - x̄)(Yi - ȳ)
         Cov( x,y) = ∑ --------------------
                    i=1      N - 1

##################################################################
@Log Normal Distribution
X = skuwed curv
"X=exp(y) or Y =log(x)"


#############################################################

"Significance Value"(α)
"Confidence Interwell" (CI)

Formula_of_to_find_out_Confidence_interwell  with "Z_TEST":= 
        
        Point Estimate ± Margin of Error
                
                [:. Point Estiamte = x̄]
                [:.Margin of Error = Zα/2]
                
                           σ  
             := x̄ ± Zα/2 ----  
                          √n 
                     σ 
         ---->     ----    this turm/formula will define our 
                    √n    'Standard Error'
            
######################################################################            
here Population SD is not given so we use "T_test"

         Point Estimate ± Margin of Error
    
                [:. Point Estiamte = x̄   ]
                [:.Margin of Error = Tα/2]
                                         
                        S 
       C.I  = x̄ ± Tα/2 ----  --> this will be my standerd error
                        √n 
####################################################################

ANOVA TEST 

1.first formula := Some_of "square_bitween"
-------------------------------------------

              ∑ (∑ai)²     T²
Ss between = --------- -  --- 
                 n         N  
    
2.second formula := Some_of "square_within"
------------------------------------------- 

                     ∑ (∑ai)²    
Ss within = ∑ Y² -  ---------  
                        n    
 meanSquare formula :=
    
    
                           Someofsqre         
"meanSquare" will find = ---------------- 
                          degrreofreedom      
    
    
@last final F_test is :=
    
     
                  MsBetween     
Finally F-test =  ---------- 
                  Mswithin  
    
    MsBetween "meanSquare_B/W"
    Mswithin  "meanSquare_Within"

In [31]:
import scipy.stats as stats

In [32]:
import seaborn as sns
import pandas as pd
import numpy as np
dataset=sns.load_dataset('tips')

In [33]:
dataset.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [34]:
pd.crosstab(dataset['sex'],dataset['smoker'])
#crosstab used for cotegorical data youll get 2X2 matrix

smoker  Yes  No
sex            
Male     60  97
Female   33  54

In [39]:
dataset_table = pd.crosstab(dataset['sex'],dataset['smoker'])
dataset_table

smoker  Yes  No
sex            
Male     60  97
Female   33  54

In [40]:
print(dataset_table)

smoker  Yes  No
sex            
Male     60  97
Female   33  54


In [42]:
dataset_table.values # it converts into numpy values as array

array([[60, 97],
       [33, 54]], dtype=int64)

In [44]:
obeserver_values = dataset_table.values 
obeserver_values

array([[60, 97],
       [33, 54]], dtype=int64)

In [54]:
val = stats.chi2_contingency(obeserver_values)
val

(0.0,
 1.0,
 1,
 array([[59.84016393, 97.15983607],
        [33.15983607, 53.84016393]]))

In [58]:
val = stats.chi2_contingency(dataset_table)
val

(0.0,
 1.0,
 1,
 array([[59.84016393, 97.15983607],
        [33.15983607, 53.84016393]]))

In [67]:
expected_values=val[3]

In [68]:
expected_values

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])